trigger:
- master

pool: 'Borealis'

variables:
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerTest'
    repository: 'julzor/test-azure'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
